trigger:
  branches:
    include:
      - main

stages:

  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        steps:
          - script: echo "🔧 Building the application..."
            displayName: "Echo Build"

  - stage: Test
    displayName: "Test Stage"
    dependsOn: Build
    jobs:
      - job: TestJob
        displayName: "Test Job"
        steps:
          - script: echo "🧪 Running tests..."
            displayName: "Echo Test"

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Test
    jobs:
      - deployment: DeployJob
        displayName: "Deploy Job"
        environment: prod-env     # 🔒 Approval required before this runs
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "🚀 Deploying to production..."
                  displayName: "Echo Deploy"
